OPEN "data.omg" FOR INPUT AS #1
INPUT #1, TimeTravel
INPUT #1, Lives
INPUT #1, BioEng
INPUT #1, BioEng2
INPUT #1, BioEng3
INPUT #1, Boom
INPUT #1, LowTroub
INPUT #1, HighTroub
INPUT #1, Idiot
INPUT #1, Find
INPUT #1, Erased
INPUT #1, Dna$
INPUT #1, Strand$
INPUT #1, Dna1
INPUT #1, DNAo$
INPUT #1, Strando$
INPUT #1, Dnao1
INPUT #1, Brown
INPUT #1, ShipCome
INPUT #1, Po$
INPUT #1, D$
INPUT #1, Tc
INPUT #1, Viral
INPUT #1, Pw$
INPUT #1, Tg
INPUT #1, Td
INPUT #1, Ta
INPUT #1, Al$
INPUT #1, Stop1
INPUT #1, Stopo1
INPUT #1, Told
INPUT #1, TimeTill
INPUT #1, TimeTill2
INPUT #1, Collided
INPUT #1, Collided2
INPUT #1, Sp
INPUT #1, MaxSp
INPUT #1, ContactMade
INPUT #1, ToldTo
INPUT #1, ScanFound
INPUT #1, Scanned
INPUT #1, FindThing
INPUT #1, Amazing
INPUT #1, ShieldFound
INPUT #1, TillPlanet
INPUT #1, GotInto
INPUT #1, ThetaLearned
INPUT #1, ThetaFound
INPUT #1, Kappa12
INPUT #1, KappaFound
INPUT #1, EPFound
INPUT #1, Study
INPUT #1, GenEngineering
INPUT #1, DNAReplication
INPUT #1, ViralStudies
INPUT #1, Physiology
INPUT #1, BioChemistry
INPUT #1, Metabolism
INPUT #1, CirculatoryStudies
INPUT #1, Anatomy
INPUT #1, HormonalControl
INPUT #1, AdvancedMedicalStudies
INPUT #1, RevivalStudies
INPUT #1, CryogenicStasis
INPUT #1, PersonDie
INPUT #1, Bomb
INPUT #1, Studying
INPUT #1, Res$
INPUT #1, CryoChambers
INPUT #1, AIStudies
INPUT #1, AIPersonality
INPUT #1, AIStudies2
INPUT #1, UpgradedComputerOperationsSystems
INPUT #1, CompUpdatedScanSys
INPUT #1, Embryology
INPUT #1, Nit%
INPUT #1, Oxy%
INPUT #1, Hyd%
INPUT #1, Hel%
INPUT #1, Arg%
INPUT #1, Neon%
INPUT #1, Chlorine%
INPUT #1, Krypton%
INPUT #1, Methane%
INPUT #1, Xenon%
INPUT #1, Temp
INPUT #1, Humid
INPUT #1, Morale
INPUT #1, AI
INPUT #1, AIPers
INPUT #1, SchizAI
INPUT #1, RTemp
INPUT #1, SubliminalMessages
INPUT #1, CompDiagnostics
INPUT #1, Propaganda
INPUT #1, SocialStudies
INPUT #1, HumanNature
INPUT #1, HumanMotives
INPUT #1, HumanPsychology
INPUT #1, MobPsychology
INPUT #1, PublicSpeaking
INPUT #1, HistoricalStudies
INPUT #1, CurEvStudies
INPUT #1, AdvJournalism
INPUT #1, AdvTerroristStudies
INPUT #1, Anger
INPUT #1, Rebels
INPUT #1, Happies
INPUT #1, HappyPercent
INPUT #1, RebelPercent
INPUT #1, AdvTelevision
INPUT #1, AdvPowerSources
INPUT #1, NuclearFission
INPUT #1, ElectricEngineering
INPUT #1, QuantumMechanics
INPUT #1, RadiationStudies
INPUT #1, Superconductivity
INPUT #1, ZeroGravPhysics
INPUT #1, SubtelepathicWaves
INPUT #1, Power
INPUT #1, SocialSciences
INPUT #1, PsychSci
INPUT #1, Show1$
INPUT #1, Show2$
INPUT #1, Show3$
INPUT #1, Show4$
INPUT #1, Show5$
INPUT #1, Show6$
INPUT #1, Show1
INPUT #1, Show2
INPUT #1, Show3
INPUT #1, Show4
INPUT #1, Show5
INPUT #1, Show6
INPUT #1, SimmerDown
INPUT #1, NuclearFusion
INPUT #1, Genetics
INPUT #1, RIAR
INPUT #1, SFAR
INPUT #1, TTAR
INPUT #1, CIAR
INPUT #1, DIAR
INPUT #1, MutantResearch
INPUT #1, MutantLeft
INPUT #1, Reproduce
INPUT #1, MutantIntellect
INPUT #1, TT
INPUT #1, MutRad
INPUT #1, MutPers
INPUT #1, MutantChem
INPUT #1, CIImmune
INPUT #1, DSImmune
INPUT #1, RDImmune
INPUT #1, TimeTakes
INPUT #1, BioEngineering
INPUT #1, MLivesTest
INPUT #1, MLives
INPUT #1, IntMLifes
INPUT #1, MBreathe
INPUT #1, MReproduce
INPUT #1, MChem
INPUT #1, M
INPUT #1, MTT
INPUT #1, MMutRad
INPUT #1, MMutantChem
INPUT #1, MCIImmune
INPUT #1, MDSImmune
INPUT #1, MRDImmune
INPUT #1, MutantBreathe
CLOSE #1
1260 PRINT : PRINT "Medical Files": PRINT
1270 PRINT "Current Doctor is Dr. Angela."
1280 PRINT "We have a number of subjects of information."
PRINT "For a list of subjects, type 'list'."
1290 PRINT : INPUT "MED>", M$: PRINT
IF M$ = "list" THEN
PRINT "Anorexia"
PRINT "Aquired Immune Deficiency Syndrome (AIDS)"
PRINT "Bulemia"
PRINT "Cranial Implosion (CI)"
PRINT "Distortive Syndrome (DS)"
PRINT "Exit"
IF Viral = 1 THEN PRINT "Hemophelic Death (HD)"
PRINT "Health Act"
PRINT "Human Infectory Virus (HIV)"
PRINT "Loican (Jayne)."
PRINT "Red Death (RD)"
PRINT "Respiratory Corruption Disease (RCD)"
PRINT "Tobacco"
END IF
IF M$ = "loican" THEN PRINT "Woman biologist that developed a cure for AIDS in the year 2018.  See HIV and": PRINT "AIDS for more information concerning AIDS."
IF M$ = "health act" THEN PRINT "The Health Act of 2065 was passed in an effort to make people stop destroying": PRINT "themselves.  Parts of the act include, 'No person shall consume tobacco,": PRINT "nicotine, narcotics, or alcohal, for these have been shown to be harmful to": PRINT "humans.  The President shall do everything in his or her power to stop illegal": PRINT "importation of these substances into America.'  After this, many wars broke out": PRINT "with America, for small countries doing much of the drug business lost a great": PRINT "deal of their money.  Eventually though, people accepted the Health Act,": PRINT "realizing it was for their own good."
IF M$ = "tobacco" THEN PRINT "Tobacco was a drug once taken by the populace of Earth.  In the later half of": PRINT "the twenty-first century, tobacco was outlawed around the world.  For another": PRINT "twenty years, illegal tobacco consumption was popular, but eventually this": PRINT "died down.  The banning of Tobacco was stated in the Health Act of 2065.  See": PRINT "'Health Act.'"
IF M$ = "HD" AND Viral = 1 THEN
PRINT "Classification:  Blood Disaster."
PRINT "Cause:  Bioengineered Disease."
PRINT "Target Group:  Any non-human."
PRINT "Cure:  None designed."
IF Find = 1 THEN
PRINT "Notes:  HD was created in Omega Blue by the station commander in an effort to"
PRINT "offset an alien race that sent the virus CI upon us.  HD is being sent off to"
PRINT "Alpha Centauri B 3 now in response to the race on Alpha Centauri sending CI to"
PRINT "Earth."
END IF
IF Find = 0 THEN PRINT "Notes:  HD was created in Omega Blue by the station commander."
END IF
IF M$ = "CI" THEN
IF BioEng = 0 THEN
PRINT "Classification:  Brain Disorder."
IF Find = 0 THEN PRINT "Cause:  Radiation Levels."
IF Find = 1 THEN PRINT "Cause: Bioengineered Disease."
PRINT "Target Group:  Any human."
PRINT "Cure:  None yet known."
PRINT "Notes:  CI first causes the brain to slow down.  Manual dexterity is greatly"
PRINT "reduced, as are reasoning skills.  Eventually, the brain begins to shrivel up,"
PRINT "caniballizing itself for the nutrients it needs.  Doctor Angela aboard the"
PRINT "space station Omega Blue is working for a cure."
END IF
IF BioEng = 1 THEN
PRINT "Classification:  Brain Disorder."
IF Find = 0 THEN PRINT "Cause:  Radiation Levels."
IF Find = 1 THEN PRINT "Cause: Bioengineered Disease."
PRINT "Target Group:  Any human."
PRINT "Cure:  A complex string on Amino Acids."
PRINT "Notes:  CI first causes the brain to slow down.  Manual dexterity is greatly"
PRINT "reduced, as are reasoning skills.  Eventually, the brain begins to shrivel up,"
PRINT "caniballizing itself for the nutrients it needs.  The cure to CI was found"
PRINT "recently by the station of Omega Blue."
END IF
END IF
IF M$ = "DS" THEN
PRINT "Classification:  Biological Deficiency."
PRINT "Cause:  Viruses"
PRINT "Target Group:  Any children."
PRINT "Cure:  None yet known."
PRINT "Notes:  DS causes the infected individual to teleport around at random.  The"
PRINT "syndrome lasts three days, and then the disease leaves, never to return."
IF BioEng2 = 1 THEN PRINT "The cure to DS was recently discovered on Omega Blue."
END IF
IF M$ = "RD" THEN
IF BioEng3 = 0 THEN
PRINT "Classification:  Disease"
PRINT "Cause:  Unknown"
PRINT "Target Group:  Any are susceptible"
PRINT "Cure:  None known"
PRINT "Notes:  Named after the disease in the ancient author Edgar Allen Poe's short"
PRINT "story, Masque of the Red Death, this disease causes blood veins to become"
PRINT "independant, with blood flowing anywhere it wants.  People ofter cough up"
PRINT "blood and feel light-headed for lack of blood from the brain.  Profuse"
PRINT "dizziness is suffered.  In less than two days after contraction of the"
PRINT "disease, the person infected dies."
END IF
IF BioEng3 = 1 THEN
PRINT "Classification:  Disease"
PRINT "Cause:  Enzymes in Blood"
PRINT "Target Group:  Any are susceptible"
PRINT "Cure:  A complex string of Deoxyribo-Nucleuic Acids."
PRINT "Notes:  Named after the disease in the ancient author Edgar Allen Poe's short"
PRINT "story, Masque of the Red Death, this disease causes blood veins to become"
PRINT "independant, with blood flowing anywhere it wants.  People ofter cough up"
PRINT "blood and feel light-headed for lack of blood from the brain.  Profuse"
PRINT "dizziness is suffered.  In less than two days after contraction of the"
PRINT "disease, the person infected dies.  The cure was recently discovered on Omega"
PRINT "Blue."
END IF
END IF
IF M$ = "RCD" THEN
PRINT "Classification:  Respitory Disease"
PRINT "Cause:  Radiation"
PRINT "Target Group:  Any are susceptible"
PRINT "Cure:  None yet known"
PRINT "Notes:  This disease eats away at the lung's protective casing, turning it"
PRINT "black, not unlike tobacco.  See 'tobacco'  Eventually, the blackness spreads,"
PRINT "killing the victim for lack of air."
END IF
IF M$ = "anorexia" THEN PRINT "Classification:  Eating Disorder.": PRINT "Cause:  Under-eating.": PRINT "Target Group:  Teen-agers, mainly females.": PRINT "Cure:  Unknown."
IF M$ = "bulemia" THEN PRINT "Classification:  Eating Disorder.": PRINT "Cause:  Over-eating.": PRINT "Target Group:  Teen-agers, mainly females.": PRINT "Cure:  Unknown."
IF M$ = "AIDS" THEN
PRINT "Classification:  Aquired Immune Deficiency Syndrome."
PRINT "Cause:  Contact between bodily fluids"
PRINT "Target Group:  Anyone is susceptible to this disease."
PRINT "Cure:  AIDS inhibitors."
PRINT "Notes:  AIDS used to be feared throughout the world in the 90's.  However,"
PRINT "soon drugs meant to slow down the virus soon prevented the AIDS virus from"
PRINT "multipling.  AIDS would shut down the human immune system, making usually"
PRINT "minor diseases like the common cold kill the AIDS infected person."
PRINT "For more information about AIDS, see HIV and Loican."
END IF
IF M$ = "HIV" THEN
PRINT "Classification:  Human Infectory Virus."
PRINT "Cause:  Contact between bodily fluids"
PRINT "Target Group:  Anyone is susceptible to the disease."
PRINT "Cure:  HIV inhibitors."
PRINT "Notes:  HIV is the virus that causes AIDS.  See AIDS for more details."
END IF
1400 IF M$ = "exit" OR M$ = "x" THEN PRINT : GOTO 190
1410 GOTO 1290
OPEN "data.omg" FOR OUTPUT AS #1
PRINT #1, TimeTravel
PRINT #1, Lives
PRINT #1, BioEng
PRINT #1, BioEng2
PRINT #1, BioEng3
PRINT #1, Boom
PRINT #1, LowTroub
PRINT #1, HighTroub
PRINT #1, Idiot
PRINT #1, Find
PRINT #1, Erased
PRINT #1, Dna$
PRINT #1, Strand$
PRINT #1, Dna1
PRINT #1, DNAo$
PRINT #1, Strando$
PRINT #1, Dnao1
PRINT #1, Brown
PRINT #1, ShipCome
PRINT #1, Po$
PRINT #1, D$
PRINT #1, Tc
PRINT #1, Viral
PRINT #1, Pw$
PRINT #1, Tg
PRINT #1, Td
PRINT #1, Ta
PRINT #1, Al$
PRINT #1, Stop1
PRINT #1, Stopo1
PRINT #1, Told
PRINT #1, TimeTill
PRINT #1, TimeTill2
PRINT #1, Collided
PRINT #1, Collided2
PRINT #1, Sp
PRINT #1, MaxSp
PRINT #1, ContactMade
PRINT #1, ToldTo
PRINT #1, ScanFound
PRINT #1, Scanned
PRINT #1, FindThing
PRINT #1, Amazing
PRINT #1, ShieldFound
PRINT #1, TillPlanet
PRINT #1, GotInto
PRINT #1, ThetaLearned
PRINT #1, ThetaFound
PRINT #1, Kappa12
PRINT #1, KappaFound
PRINT #1, EPFound
PRINT #1, Study
PRINT #1, GenEngineering
PRINT #1, DNAReplication
PRINT #1, ViralStudies
PRINT #1, Physiology
PRINT #1, BioChemistry
PRINT #1, Metabolism
PRINT #1, CirculatoryStudies
PRINT #1, Anatomy
PRINT #1, HormonalControl
PRINT #1, AdvancedMedicalStudies
PRINT #1, RevivalStudies
PRINT #1, CryogenicStasis
PRINT #1, PersonDie
PRINT #1, Bomb
PRINT #1, Studying
PRINT #1, Res$
PRINT #1, CryoChambers
PRINT #1, AIStudies
PRINT #1, AIPersonality
PRINT #1, AIStudies2
PRINT #1, UpgradedComputerOperationsSystems
PRINT #1, CompUpdatedScanSys
PRINT #1, Embryology
PRINT #1, Nit%
PRINT #1, Oxy%
PRINT #1, Hyd%
PRINT #1, Hel%
PRINT #1, Arg%
PRINT #1, Neon%
PRINT #1, Chlorine%
PRINT #1, Krypton%
PRINT #1, Methane%
PRINT #1, Xenon%
PRINT #1, Temp
PRINT #1, Humid
PRINT #1, Morale
PRINT #1, AI
PRINT #1, AIPers
PRINT #1, SchizAI
PRINT #1, RTemp
PRINT #1, SubliminalMessages
PRINT #1, CompDiagnostics
PRINT #1, Propaganda
PRINT #1, SocialStudies
PRINT #1, HumanNature
PRINT #1, HumanMotives
PRINT #1, HumanPsychology
PRINT #1, MobPsychology
PRINT #1, PublicSpeaking
PRINT #1, HistoricalStudies
PRINT #1, CurEvStudies
PRINT #1, AdvJournalism
PRINT #1, AdvTerroristStudies
PRINT #1, Anger
PRINT #1, Rebels
PRINT #1, Happies
PRINT #1, HappyPercent
PRINT #1, RebelPercent
PRINT #1, AdvTelevision
PRINT #1, AdvPowerSources
PRINT #1, NuclearFission
PRINT #1, ElectricEngineering
PRINT #1, QuantumMechanics
PRINT #1, RadiationStudies
PRINT #1, Superconductivity
PRINT #1, ZeroGravPhysics
PRINT #1, SubtelepathicWaves
PRINT #1, Power
PRINT #1, SocialSciences
PRINT #1, PsychSci
PRINT #1, Show1$
PRINT #1, Show2$
PRINT #1, Show3$
PRINT #1, Show4$
PRINT #1, Show5$
PRINT #1, Show6$
PRINT #1, Show1
PRINT #1, Show2
PRINT #1, Show3
PRINT #1, Show4
PRINT #1, Show5
PRINT #1, Show6
PRINT #1, SimmerDown
PRINT #1, NuclearFusion
PRINT #1, Genetics
PRINT #1, RIAR
PRINT #1, SFAR
PRINT #1, TTAR
PRINT #1, CIAR
PRINT #1, DIAR
PRINT #1, MutantResearch
PRINT #1, MutantLeft
PRINT #1, Reproduce
PRINT #1, MutantIntellect
PRINT #1, TT
PRINT #1, MutRad
PRINT #1, MutPers
PRINT #1, MutantChem
PRINT #1, CIImmune
PRINT #1, DSImmune
PRINT #1, RDImmune
PRINT #1, TimeTakes
PRINT #1, BioEngineering
PRINT #1, MLivesTest
PRINT #1, MLives
PRINT #1, IntMLifes
PRINT #1, MBreathe
PRINT #1, MReproduce
PRINT #1, MChem
PRINT #1, M
PRINT #1, MTT
PRINT #1, MMutRad
PRINT #1, MMutantChem
PRINT #1, MCIImmune
PRINT #1, MDSImmune
PRINT #1, MRDImmune
PRINT #1, MutantBreathe
CLOSE #1
RUN "omega.bas"

