OPEN "data.omg" FOR INPUT AS #1
INPUT #1, TimeTravel
INPUT #1, Lives
INPUT #1, BioEng
INPUT #1, BioEng2
INPUT #1, BioEng3
INPUT #1, Boom
INPUT #1, LowTroub
INPUT #1, HighTroub
INPUT #1, Idiot
INPUT #1, Find
INPUT #1, Erased
INPUT #1, Dna$
INPUT #1, Strand$
INPUT #1, Dna1
INPUT #1, DNAo$
INPUT #1, Strando$
INPUT #1, Dnao1
INPUT #1, Brown
INPUT #1, ShipCome
INPUT #1, Po$
INPUT #1, D$
INPUT #1, Tc
INPUT #1, Viral
INPUT #1, Pw$
INPUT #1, Tg
INPUT #1, Td
INPUT #1, Ta
INPUT #1, Al$
INPUT #1, Stop1
INPUT #1, Stopo1
INPUT #1, Told
INPUT #1, TimeTill
INPUT #1, TimeTill2
INPUT #1, Collided
INPUT #1, Collided2
INPUT #1, Sp
INPUT #1, MaxSp
INPUT #1, ContactMade
INPUT #1, ToldTo
INPUT #1, ScanFound
INPUT #1, Scanned
INPUT #1, FindThing
INPUT #1, Amazing
INPUT #1, ShieldFound
INPUT #1, TillPlanet
INPUT #1, GotInto
INPUT #1, ThetaLearned
INPUT #1, ThetaFound
INPUT #1, Kappa12
INPUT #1, KappaFound
INPUT #1, EPFound
INPUT #1, Study
INPUT #1, GenEngineering
INPUT #1, DNAReplication
INPUT #1, ViralStudies
INPUT #1, Physiology
INPUT #1, BioChemistry
INPUT #1, Metabolism
INPUT #1, CirculatoryStudies
INPUT #1, Anatomy
INPUT #1, HormonalControl
INPUT #1, AdvancedMedicalStudies
INPUT #1, RevivalStudies
INPUT #1, CryogenicStasis
INPUT #1, PersonDie
INPUT #1, Bomb
INPUT #1, Studying
INPUT #1, Res$
INPUT #1, CryoChambers
INPUT #1, AIStudies
INPUT #1, AIPersonality
INPUT #1, AIStudies2
INPUT #1, UpgradedComputerOperationsSystems
INPUT #1, CompUpdatedScanSys
INPUT #1, Embryology
INPUT #1, Nit%
INPUT #1, Oxy%
INPUT #1, Hyd%
INPUT #1, Hel%
INPUT #1, Arg%
INPUT #1, Neon%
INPUT #1, Chlorine%
INPUT #1, Krypton%
INPUT #1, Methane%
INPUT #1, Xenon%
INPUT #1, Temp
INPUT #1, Humid
INPUT #1, Morale
INPUT #1, AI
INPUT #1, AIPers
INPUT #1, SchizAI
INPUT #1, RTemp
INPUT #1, SubliminalMessages
INPUT #1, CompDiagnostics
INPUT #1, Propaganda
INPUT #1, SocialStudies
INPUT #1, HumanNature
INPUT #1, HumanMotives
INPUT #1, HumanPsychology
INPUT #1, MobPsychology
INPUT #1, PublicSpeaking
INPUT #1, HistoricalStudies
INPUT #1, CurEvStudies
INPUT #1, AdvJournalism
INPUT #1, AdvTerroristStudies
INPUT #1, Anger
INPUT #1, Rebels
INPUT #1, Happies
INPUT #1, HappyPercent
INPUT #1, RebelPercent
INPUT #1, AdvTelevision
INPUT #1, AdvPowerSources
INPUT #1, NuclearFission
INPUT #1, ElectricEngineering
INPUT #1, QuantumMechanics
INPUT #1, RadiationStudies
INPUT #1, Superconductivity
INPUT #1, ZeroGravPhysics
INPUT #1, SubtelepathicWaves
INPUT #1, Power
INPUT #1, SocialSciences
INPUT #1, PsychSci
INPUT #1, Show1$
INPUT #1, Show2$
INPUT #1, Show3$
INPUT #1, Show4$
INPUT #1, Show5$
INPUT #1, Show6$
INPUT #1, Show1
INPUT #1, Show2
INPUT #1, Show3
INPUT #1, Show4
INPUT #1, Show5
INPUT #1, Show6
INPUT #1, SimmerDown
INPUT #1, NuclearFusion
INPUT #1, Genetics
INPUT #1, RIAR
INPUT #1, SFAR
INPUT #1, TTAR
INPUT #1, CIAR
INPUT #1, DIAR
INPUT #1, MutantResearch
INPUT #1, MutantLeft
INPUT #1, Reproduce
INPUT #1, MutantIntellect
INPUT #1, TT
INPUT #1, MutRad
INPUT #1, MutPers
INPUT #1, MutantChem
INPUT #1, CIImmune
INPUT #1, DSImmune
INPUT #1, RDImmune
INPUT #1, TimeTakes
INPUT #1, BioEngineering
INPUT #1, MLivesTest
INPUT #1, MLives
INPUT #1, IntMLifes
INPUT #1, MBreathe
INPUT #1, MReproduce
INPUT #1, MChem
INPUT #1, M
INPUT #1, MTT
INPUT #1, MMutRad
INPUT #1, MMutantChem
INPUT #1, MCIImmune
INPUT #1, MDSImmune
INPUT #1, MRDImmune
INPUT #1, MutantBreathe
CLOSE #1
BEEP: BEEP: BEEP: BEEP
PRINT "Time Travel Program Activated!"
PRINT "Downloading information......": FOR T = 1 TO 1000: STERNESS = 0: NEXT T
BEEP: BEEP: BEEP: BEEP
PRINT "Information Downloaded!"
PRINT "Launching Probes......": FOR T = 1 TO 1000: STERNESS = 0: NEXT T
BEEP: BEEP: BEEP: BEEP
PRINT "Probes launched!"
PRINT "Creating Temporal Portal......": FOR T = 1 TO 1000: STERNESS = 0: NEXT T
PRINT "Temporal Portal opened!"
INPUT "", A$: CLS
PRINT "Enter Destinations:"
PRINT "1.  Kappa 2"
PRINT "2.  Omicron 1"
PRINT "3.  Epsilon 4"
PRINT "4.  Theta 1"
PRINT "5.  Alpha Centauri B 3"
PRINT "6.  Earth"
1 PRINT : PRINT "Enter Destination of first probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 1
DEST1 = A
IF DEST1 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 1
2 PRINT : PRINT "Enter Destination of second probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 2
IF DEST1 <> A THEN DEST2 = A
IF DEST2 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 2
3 PRINT : PRINT "Enter Destination of third probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 3
IF DEST1 <> A AND DEST2 <> A THEN DEST3 = A
IF DEST3 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 3
4 PRINT : PRINT "Enter Destination of fourth probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 4
IF DEST1 <> A AND DEST2 <> A AND DEST3 <> A THEN DEST4 = A
IF DEST4 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 4
5 PRINT : PRINT "Enter Destination of fifth probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 5
IF DEST1 <> A AND DEST2 <> A AND DEST3 <> A AND DEST4 <> A THEN DEST5 = A
IF DEST5 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 5
6 PRINT : PRINT "Enter Destination of sixth (and last) probe:": PRINT
INPUT "DESTINATION>", A: PRINT
IF A > 6 OR A <= 0 THEN GOTO 6
IF DEST1 <> A AND DEST2 <> A AND DEST3 <> A AND DEST4 <> A AND DEST5 <> A THEN DEST6 = A
IF DEST6 = 0 THEN PRINT "That target is being targetted by another probe.": GOTO 6
PRINT "Destination of Probe 1:   Target"; DEST1
PRINT "Destination of Probe 2:   Target"; DEST2
PRINT "Destination of Probe 3:   Target"; DEST3
PRINT "Destination of Probe 4:   Target"; DEST4
PRINT "Destination of Probe 5:   Target"; DEST5
PRINT "Destination of Probe 6:   Target"; DEST6
PRINT "Probes Launched!!!": FOR T = 1 TO 1000: NEXT T
INPUT "", A$: CLS
PRINT "Tracking Probes through time......": FOR T = 1 TO 1000: NEXT T
PRINT "Probe"; DEST1; "has crashed into Kappa 2. --- Year 263 A.D."
PRINT "Probe"; DEST2; "has crashed into Omicron 1. --- Year 203 B.C."
PRINT "Probe"; DEST3; "has crashed into Epsilon 4. --- Year 0 A.D."
PRINT "Probe"; DEST4; "has crashed into Theta 1. --- Year 1203 B.C."
PRINT "Probe"; DEST5; "has crashed into Alpha Centauri B 3. --- Year 34 A.D."
PRINT "Probe"; DEST6; "has crashed into Earth --- Year 1203 A.D."
FOR T = 1 TO 500
F = INT(RND * 10) + 1
IF F = 1 THEN PRINT "AGU";
IF F = 2 THEN PRINT "AAU";
IF F = 3 THEN PRINT "GAU";
IF F = 4 THEN PRINT "CGC";
IF F = 5 THEN PRINT "AUG";
IF F = 6 THEN PRINT "CAU";
IF F = 7 THEN PRINT "CCC";
IF F = 8 THEN PRINT "GGG";
IF F = 9 THEN PRINT "AAA";
IF F = 10 THEN PRINT "UUU";
NEXT T
FOR T = 1 TO 25
IF D = 1 THEN PRINT "1.  Cranial Implosion (CI)";
IF D = 2 THEN PRINT "2.  Distortive Syndrome (DS)";
IF D = 3 THEN PRINT "3.  Red Death (RD)";
IF D = 4 THEN PRINT "4.  Respiratory Corruption Disease (RCD)";
IF D = 5 THEN PRINT "5.  Exit";
D = D + 1
IF D = 6 THEN D = 1
NEXT T
FOR T = 1 TO 22
IF T = 1 THEN
PRINT "Our race was a race of men similar to that of the animal we have seen on other"
PRINT "worlds, called deer.  ";
END IF
IF T = 2 THEN
PRINT "When we were primative, we were violent and war-like.  Eventually a dictator-"
PRINT "ship emerged.  ";
END IF
IF T = 3 THEN
PRINT "Soon, we realized that our star was too active to have safe life on its"
PRINT "planets.  ";
END IF
IF T = 4 THEN
PRINT "Early in our history, our people were a warring people.  ";
END IF
IF T = 5 THEN
PRINT "Our technology has nothing to do with weapons.  ";
END IF
IF T = 6 THEN
PRINT "Eventually, there was a revolution against David the Powerful, who was killed"
PRINT "by a hideous disease known as CI.  CI was engineered using information on the";
END IF
IF T = 7 THEN
PRINT "We know not what our future holds.  Perhaps trancendency to gods -- or more."
PRINT "We are soon increasing our population.  Soon Epsilon 4 will be too small for";
END IF
IF T = 8 THEN
PRINT "Soon, those left on Epsilon 4 became lazy and created a fertile utopia, in"
PRINT "which medicine was highly stressed.  Although the probe contained other";
END IF
IF T = 9 THEN
PRINT "Technology was for the weak.  The probe that landed gave us all of the weapon"
PRINT "technology we need to know.";
END IF
IF T = 10 THEN
PRINT "Either the star will calm down from its solar flares or we will perish.";
END IF
IF T = 11 THEN
PRINT "The new technology we found was a time travel program contained on it.  We"
PRINT "travelled through our history's past, killing the main leaders of our wars.";
END IF
IF T = 12 THEN
PRINT "Technology Level:  We have limited space travel and medical programs.  Our"
PRINT "world is one where monorails move along the tundra, taking us from one city";
END IF
IF T = 13 THEN
PRINT "that we could build to escape our world.  Instead of having five people escape,"
PRINT "a theory was developed that we could send the shuttle into the star, and if";
END IF
IF T = 14 THEN
PRINT "Thruster stability seems to be holding.  However, the Thrusters will only take"
PRINT "the Station 100 kms an hour.";
END IF
IF T = 15 THEN
PRINT "From all evidence, this strand appears to be a cure for the DS disease."
PRINT "Sending a read-out of information found to Doctor Angela.";
END IF
IF T = 16 THEN
PRINT "1; which was dying anyway.  Simple.  Alpha Centauri B 3 was also dying, easy"
PRINT "to control.  Then there was Kappa 2.  We conquered Kappa 2 just before we"
PRINT "realized the horrible truth... our race was dying.";
END IF
IF T = 17 THEN
PRINT "comprehension.  However, on the machine was a program that enhanced the"
PRINT "intellegence rate of the people.  Soon the wars ended, and civilization took";
END IF
IF T = 18 THEN
PRINT "a theory was developed that we could send the shuttle into the star, and if"
PRINT "the proper chemicals were on that shuttle, the star might calm down.  We";
END IF
IF T = 19 THEN
PRINT "Violence was then purged from our midst.  ";
END IF
IF T = 20 THEN
PRINT "We have everything before us --- we have nothing before us.  ";
END IF
IF T = 21 THEN
PRINT "This is the essence of our lives, Hereg–l.  ";
END IF
IF T = 22 THEN
PRINT "The book of Forbidden Lore.  ";
END IF
NEXT T
FOR T = 1 TO 100
COLOR 0, 0: CLS
COLOR 15, 15: CLS
NEXT T
DD: COLOR 15, 0: CLS
PRINT "Omega Blue Computer Control System": PRINT
PRINT "Original CCS Copyright 1701."
PRINT "Integrated into Station Command in 1708. "
PRINT "Integrated into Omega Blue in 1716."
PRINT "Current Year: 1800.": PRINT
INPUT "", A$
SC = 0
PRINT "Ships crashed                    -1 each:"; Boom: SC = SC + (Boom * -1)
PRINT "Shut Power off                   -5 each:"; Idiot: SC = SC + (Idiot * -5)
PRINT "Brown-outs                       -3 each:"; LowTroub: SC = SC + (LowTroub * -3)
PRINT "Explosions                       -3 each:"; HighTroub: SC = SC + (HighTroub * -3)
PRINT "Cures engineered                 +5 each:"; 5 * (BioEng + BioEng2 + BioEng3): SC = SC + (5 * (BioEng + BioEng2 + BioEng3))
PRINT "Alien Races found                +3 each:"; (Find + ToldTo + FindThing) * 3: SC = SC + 3 * (Find + ToldTo + FindThing)
PRINT "Virus's Engineered               +5 each:"; Viral * 5: SC = SC + Viral * 5
PRINT "Alien technologies found         +5 each:"; (TimeTravel + ShieldFound + Amazing + ScanFound) * 5: SC = SC + (TimeTravel + ScanFound + Amazing + ShieldFound) * 5
PRINT "Lives left               +1 for each 100:"; INT(Lives / 100): SC = SC + INT(Lives / 100)
PRINT
PRINT "Total Score                              "; SC
PRINT : PRINT "Thanks to you, humanity will spread throughout the stars, colonizing the"
PRINT "worlds safely and peacefully."
PRINT : INPUT "Do you want to play again?", A$: PRINT
IF MID$(A$, 1, 1) = "y" THEN RUN
COLOR 0: END

