'RoomDesc
'
'Room Description Here
'
'End Desc
'Directions here
'STOP

Tube East-West
Start
Current Position:  In East-West Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
east and west.
EndDesc
East
West
STOP

Tube North-South
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.
EndDesc
North
South
STOP

City Entrance - Closed - Device Open
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  It is opened, and under it there is extensive
circuitry and wiring.  There also appears to be a lever in the device also.
Next to the device is a door, currently closed.  On the door is some writing.
To the south, the tubing continues on.
EndDesc
South
STOP

City Entrance - Closed
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  On the odd device appears to be a red button
and a keypad.  Next to the device is a door, currently closed.  On the door
is some writing.  To the south, the tubing continues on.
EndDesc
South
STOP

City Entrance - Opened
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  On the odd device appears to be a red button
and a keypad.  Next to the device is a door, currently open.  On the door is
some writing.  To the south, the tubing continues on.
EndDesc
North
South
STOP

City Entrance - Opened - Device Open
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  It is opened, and under it there is extensive
circuitry and wiring.  There also appears to be a lever in the device also.
Next to the device is a door, currently open.  On the door is some writing.
To the south, the tubing continues on.
EndDesc
North
South
STOP


Tube North-South - Power Unfixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a broken power line in the wall here in the east 
wall.
EndDesc
North
South
STOP

Tube North-South - Power Half Fixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a power line in the wall here in the east 
wall.  There is a power couplink lying over it, currently not welded to the
power line.
EndDesc
North
South
STOP

Tube North-South - Power Fixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a fixed power line in the wall here in the east 
wall.  At times, it gives off electrical sparks, but it seems to work.
EndDesc
North
South
STOP

Blocked Tube - Power Half Fixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system reports
no chemical atmosphere past collapsed tube.  The tubing here continues to 
the north.  There is a power line in the wall here in the east wall.  On it
is a power couplink.  The couplink is not welded on to the power line.  In 
the rubble of the collapsed tube is a contained fission explosive.
EndDesc
North
STOP

Blocked Tube - Power Fixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system reports
no chemical atmosphere past collapsed tube.  The tubing here continues to 
the north.  There is a fixed power line in the wall here in the east wall.  
At times, it gives off electrical sparks, but it seems to work.  On the 
rubble of the collapsed tube is a contained fission explosive.
EndDesc
North
STOP

Blocked Tube - Power Unfixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a broken power line in the wall here in the
east wall.  On the rubble of the collapsed tube is a contained fission 
explosive.
EndDesc
North
STOP

Blocked Tube - Power Half Fixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is power line in the wall here in the east 
wall.  Placed over it is a power couplink which is not welded to the line.
There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Blocked Tube - Power Fixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a fixed power line in the wall here in the
east wall.  At times, it gives off electrical sparks, but it seems to work.
There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Blocked Tube - Power Unfixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a broken power line in the wall here in the
east wall.  There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Power Conduit
Start
Current Position:  In Tube

        Visual sensors report that the eastern tube ends here.  The tube
goes off to the west from here.  Sensors indicate a vacuum outside the
current tube area.  There is a large device in the east wall here.
EndDesc
West
STOP

Outside Biolab - Door Closed
Start
Current Position:  In Tube

        Visual sensors report there to be a closed door in the south wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  On the door appears to be a symbol and some writing.  Next
to the door is a slot.
EndDesc
West
East
STOP

Outside Biolab - Door Opened
Start
Current Position:  In Tube

        Visual sensors report there to be a open door in the south wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  Next to the door is a slot.
EndDesc
South
West
East
STOP

Tube Intersection
Start
Current Position:  Tube Intersection

        Visual sensors report there to be an open door in the south wall
here.  Sensors report an intersection of tubes comprised mostly of plastic
here.  Outside the tubes is a planetary vacuum.  No atmosphere detected
beyond tubing.  The tubes go off to the north, east, and west.  The door
is open to the south.
EndDesc
North
South
East
West
STOP

Outside Library or Security - Door Opened
Start
Current Position:  In Tube

        Visual sensors report there to be a opened door in the north wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  Next to the door is a slot.
EndDesc
North
East
West
STOP

Outside Library or Security - Door Closed
Start
Current Position:  In Tube

        Visual sensors report there to be a closed door in the north wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  On the door appears to be some writing.  Next to the door
is a slot.
EndDesc
West
East
STOP

Tube North-East
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and east.
EndDesc
North
East
STOP

Tube South-West
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
south and west.
EndDesc
South
West
STOP

Tube South-East
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
south and east.
EndDesc
South
East
STOP

Sterilization Chamber2 - Outer Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  The one to the
north is open.
EndDesc
North
STOP

Sterilization Chamber2 - Inner Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  The one to the
west is open.
EndDesc
West
STOP

Sterilization Chamber2 - Closed
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  Both are closed.
EndDesc
STOP

Sterilization Chamber - Outer Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  The one to the
north is open.
EndDesc
North
STOP

Sterilization Chamber - Inner Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  The one to the
south is open.
EndDesc
South
STOP

Sterilization Chamber - Closed
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  Both are closed.
EndDesc
STOP

Lobby - Closed
Start
Current Position:  White Room

        Sensors indicate Current Position to be within a white room.  There
is a computer terminal behind a desk here, with a red power button on it.
There is a closed door to the north, with a slot next to it.  Below the
slot is an electronic keypad and screen.  There is a hallway to the west.
EndDesc
West
STOP

Lobby - Open
Start
Current Position:  White Room

        Sensors indicate Current Position to be within a white room.  There
is a computer terminal behind a desk here, with a red power button on it.
There is an open door to the north, with a slot next to it.  Below the
slot is an electronic keypad and screen.  There is a hallway to the west.
EndDesc
North
West
STOP

Library Core
Start
Current Position:  Library Core

        Visual sensors report Current Position to be what seems to be the
equivalent of a library.  There are no books here, but there appears to be
a large amount of circuitry built in the walls here.  There is an open
archway to the east, where a large deal of the circuitry is detected.  There
is a doorway to the south, currently open.
EndDesc
East
South
STOP

Library Central Computer
Start
Current Position:  Library Central Computer Core

        Visual sensors report a large mainframe in this room.  There is a
large red power button next to the mainframe.  To the west is the Central
Library Core, and the exit.  The only feature of this room is the mainframe,
which is larger than any mainframe on internal records.
EndDesc
West
STOP

Security Armory
Start
Current Position:  Weapons Depot
EndDesc
South
STOP

Debriefing Room
Start
Current Position:  Large Room
EndDesc
South
STOP

Moniter Room - Video Playing
Start
Current Position:  Surveillance Center

        Sensors indicate current area to be a surveillance center for the
domed colony on Sirrus 5.  All but one of the monitors seems to have burned
out.  The lone monitor that is not burned out is playing some sort of video.
Below the monitor is a video slot, which has a video tape in it.  It is
currently playing.  There are a set of detailed controls below the monitors.
You may leave to the south.
EndDesc
South
STOP

Moniter Room
Start
Current Position:  Surveillance Center

        Sensors indicate current area to be a surveillance center for the
domed colony on Sirrus 5.  All but one of the monitors seems to have burned
out.  The lone monitor that is not burned out is monitoring an area of the
colony.  Below the monitor is a video slot, which has a video tape in it.  
There are a set of detailed controls below the monitors.  You may leave to 
the south.
EndDesc
South
STOP

Security Hall, West
Start
Current Position:  In Hallway

        Current position is within a long hallway.  The hallway continues to
the east and west.  There is an open doorway to the north from here.
EndDesc
West
North
East
STOP

Security Hall, East
Start
Current Position:  In Hallway

        Current position is within a long hallway.  The hallway continues to
the west.  There is an open doorway to the north from here.
EndDesc
West
North
STOP

Security Access
Start
Current Position:  Security Lobby

        Visual sensors report current position to be in a white-walled lobby.
There is a computer here, currently off.  Next to the computer is a red
button, inlaid with circuitry.  There is a long hallway to the east from
here, and there is a large room to the north.  There is a door to the south
from here, currently open.
EndDesc
North
East
South
STOP

Outside BioDome - Near Door - NorthEast Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the west, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the south, along the wall of the
biosphere.
EndDesc
West
South
STOP

Outside BioDome - Near Door - NorthWest Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the east, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the south, along the wall of the
biosphere.
EndDesc
East
South
STOP

Outside BioDome - Near Door - West Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the east, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the north and southeast, along the 
wall of the biosphere.
EndDesc
East
North
SouthEast
STOP

Outside BioDome - Near Door - East Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the west, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the north and southwest, along the 
wall of the biosphere.
EndDesc
West
North
SouthWest
STOP

Outside BioDome - East Side
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  From current location, sensors indicate movement is possible to the 
north and south, along the wall of the biosphere, which is to the west.
EndDesc
North
South
STOP

Outside BioDome - West Side
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  From current location, sensors indicate movement is possible to the 
north and south, along the wall of the biosphere, which is to the east.
EndDesc
North
South
STOP

Outside BioDome - Near Door - SouthWest Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the east, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the northwest, along the wall of 
the biosphere.
EndDesc
East
NorthWest
STOP

Outside BioDome - Near Door - SouthEast Entrance
Start
Current Position:  Outside Biodome

        Visual sensors report current position to be in the space between the
outside of the habitation area of the Sirrus 5 colony and the security force
field.  There is an airlock door to the west, which is set to open when 
anything moves close enough to it.  Since there is no atmospheric or pressure
differences between current position and inside habitation area, this is
possible without a sterilization and decontamination chamber.  From here,
sensors indicate movement is possible to the northeast, along the wall of 
the biosphere.
EndDesc
West
NorthEast
STOP

Computer Console - Room 38
Start
Current Position:  East-West Hallway

        Visual sensors report current position to be in a featureless 
east-west hallway.  There is a computer console in the south wall here, next 
to which is a green button.  To the north is an automatic sliding door with
some writing on it.
EndDesc
East
North
West
STOP

Computer Console
Start
Current Position:  East-West Hallway

        Visual sensors report current position to be in a featureless 
east-west hallway.  There is a computer console in the south wall here, next 
to which is a green button.
EndDesc
East
West
STOP

Outside Door - PC45 - Closed
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the east.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the south, which is closed.  Next to the
door is a keypad and small electronic display.  A hall continues to the west.
EndDesc
East
West
STOP

Outside Door - PC45 - Open
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the east.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the south, which is opened.  Next to the
door is a keypad and small electronic display.  A hall continues to the west.
EndDesc
East
South
West
STOP

Outside Door - TE32 - Closed
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the west.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the south, which is closed.  Next to the
door is a keypad and small electronic display.  A hall continues to the east.
EndDesc
East
West
STOP

Outside Door - TE32 - Open
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the west.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the south, which is opened.  Next to the
door is a keypad and small electronic display.  A hall continues to the east.
EndDesc
East
South
West
STOP

Living Quarters - TE32 - Closed - Welder Taken
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
north, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - TE32 - Closed - Welder Untaken
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  The sole thing on the
shelves is a laser-operated welder.  There is a door to the north, which is
closed.  Next to the door is a single button.  There is an electrical socket
in the wall here.
EndDesc
STOP

Living Quarters - TE32 - Open - Welder Taken
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
north, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
North
STOP

Living Quarters - TE32 - Open - Welder Untaken
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  The sole thing on the
shelves is a laser-operated welder.  There is a door to the north, which is
opened.  Next to the door is a single button.  There is an electrical socket
in the wall here.
EndDesc
North
STOP

Living Quarters - PC45 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
north, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - PC45 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
north, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
North
STOP

Living Quarters - TE43 - Open - Couplinks Taken
Start
Current Position:  Living Quarters        
        
        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is an open door
to the west.  Next to the door is a single button.  There is an electrical
socket in the wall here.
EndDesc
West
STOP

Living Quarters - TE43 - Open - Couplinks Untaken
Start
Current Position:  Living Quarters        
        
        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  The sole thing on the
shelves is a power couplink.  There is a door to the west, which is opened.  
Next to the door is a single button.  There is an electrical socket in the 
wall here.
EndDesc
West
STOP

Living Quarters - TE43 - Closed - Couplinks Taken
Start
Current Position:  Living Quarters        
        
        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a closed door
to the west.  Next to the door is a single button.  There is an electrical
socket in the wall here.
EndDesc
STOP

Living Quarters - TE43 - Closed - Couplinks Untaken
Start
Current Position:  Living Quarters        
        
        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  The sole thing on the
shelves is a power couplink.  There is a door to the west, which is closed.
Next to the door is a single button.  There is an electrical socket in the 
wall here.
EndDesc
STOP

Living Quarters - MO12355 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - MO12355 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
East
STOP

Living Quarters - SO351326 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - SO351326 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
East
STOP

Living Quarters - SO341451 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - SO341451 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
east, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
East
STOP

Living Quarters - MO54382 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
south, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - MO54382 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
south, which is opened.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
South
STOP

Living Quarters - SO426274 - Closed
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
south, which is closed.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
STOP

Living Quarters - SO426274 - Open
Start
Current Position:  Living Quarters

        Sensors detect this area to be some sort of habitation cell.  There
is a set of cabinets and shelves on the wall here.  There is a door to the 
south, which is open.  Next to the door is a single button.  There is an
electrical socket in the wall here.
EndDesc
South
STOP

Outside Door - SO426274 - Closed
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the east.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the north, which is closed.  Next to the
door is a keypad and small electronic display.  A hall continues to the west.
EndDesc
East
North
West
STOP

Outside Door - SO426274 - Open
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the east.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the south, which is opened.  Next to the
door is a keypad and small electronic display.  A hall continues to the west.
EndDesc
East
West
STOP

Outside Door - MO54382 - Closed
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the west.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the north, which is closed.  Next to the
door is a keypad and small electronic display.  A hall continues to the east.
EndDesc
East
West
STOP

Outside Door - MO54382 - Open
Start
Current Position:  Near Airlock Door

        Visual sensors report current position to be near an airlock door, to
the west.  Sensors detect airlock door to be motion-sensitive.  Sensors also 
detect no pressure or atmospheric differences between the outside and current
position.  There is also a door to the north, which is opened.  Next to the
door is a keypad and small electronic display.  A hall continues to the east.
EndDesc
East
North
West
STOP

Tube Intersection - Room 60
Start
Current Position:  Tube Intersection

        Visual sensors report position to be at the intersection of three
seperate tubes, coming in from the north, east, and west.  There is a closed
door to the south here, with radiation symbols embossed on it.  Next to the
door is a keypad, a slot, and an electric screen.
EndDesc
North
East
West
STOP

Reactor 1 - Closed
Start
Current Position:  Near Reactor #1

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is closed.  There 
are automatic sliding doors to the east, southeast, and west.  In the south 
wall here is embossed a large number, "1."
EndDesc
East
SouthEast
West
STOP

Reactor 2 - Closed
Start
Current Position:  Near Reactor #2

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is closed.  There 
are automatic sliding doors to the west, southwest, and east.  In the south 
wall here is embossed a large number, "2."
EndDesc
East
SouthWest
West
STOP

Reactor 3 - Closed
Start
Current Position:  Near Reactor #3

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is closed.  There 
is an automatic door to the east.  In the south wall here is embossed a 
large number, "3."
EndDesc
East
STOP

Reactor 4 - Closed
Start
Current Position:  Near Reactor #4

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is closed.  There 
is an automatic door to the west.  In the south wall here is embossed a large
number, "4."
EndDesc
West
STOP

Reactor 1 - Open
Start
Current Position:  Near Reactor #1

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is open.  There are
automatic sliding doors to the east, southeast, and west.  In the south wall 
here is embossed a large number, "1."
EndDesc
East
SouthEast
West
STOP

Reactor 2 - Open
Start
Current Position:  Near Reactor #2

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is open.  There are
automatic sliding doors to the west, southwest, and east.  In the south wall 
here is embossed a large number, "2."
EndDesc
East
SouthWest
West
STOP

Reactor 3 - Open
Start
Current Position:  Near Reactor #3

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is open.  There is
an automatic door to the east.  In the south wall here is embossed a large 
number, "3."
EndDesc
East
STOP

Reactor 4 - Open
Start
Current Position:  Near Reactor #4

        Sensors indicate position to be near a fusion reactor.  The reactor
is 12 meters high.  In its side is an access panel, which is open.  There is
an automatic door to the west.  In the south wall here is embossed a large 
number, "4."
EndDesc
West
STOP

Power Central Core - Elevator Open
Start
Current Position:  Power Nexus

        Sensors indicate position to be in a junction of five different 
rooms.  There are sliding doors to the east, west, northeast, and northwest
from here, while there is another room to the north.  There is a computer
terminal mounted into the wall here, next to which is a button.  Under the
terminal is an electrical socket.  There is a slot in the south wall here,
next to which are two open doors.  Beyond the two open doors appears to be
a small room.
EndDesc
South
East
West
NorthEast
NorthWest
STOP

Power Central Core - Elevator Closed
Start
Current Position:  Power Nexus

        Sensors indicate position to be in a junction of five different 
rooms.  There are sliding doors to the east, west, northeast, and northwest
from here, while there is another room to the north.  There is a computer
terminal mounted into the wall here, next to which is a button.  Under the
terminal is an electrical socket.  There is a slot in the south wall here,
next to which is a set of two closed doors.
EndDesc
North
South
East
West
NorthEast
NorthWest
STOP

Elevator - Doors Closed - Panel Open
Start
Current Position:  Tiny Chamber

        Sensors indicate current position to be inside a tiny chamber.   
There is a red button above a blue button here.  Next to the buttons is an
electric socket.  There is a open panel in the wall here.  There is a
pair of closed doors to the north here.  In the panel is a yellow button.
EndDesc
STOP

Elevator - Doors Closed - Panel Closed
Start
Current Position:  Tiny Chamber

        Sensors indicate current position to be inside a tiny chamber.   
There is a red button above a blue button here.  Next to the buttons is an
electric socket.  There is a closed panel in the wall here.  There is a
pair of closed doors to the north here.
EndDesc
STOP

Elevator - Doors Open - Panel Open
Start
Current Position:  Tiny Chamber

        Sensors indicate current position to be inside a tiny chamber.   
There is a red button above a blue button here.  Next to the buttons is an
electric socket.  There is a open panel in the wall here.  There is a
pair of open doors to the north here.  In the panel is a yellow button.
EndDesc
North
STOP

Elevator - Doors Open - Panel Closed
Start
Current Position:  Tiny Chamber

        Sensors indicate current position to be inside a tiny chamber.   
There is a red button above a blue button here.  Next to the buttons is an
electric socket.  There is a closed panel in the wall here.  There is a
pair of open doors to the north here.
EndDesc
North
STOP

Shuttle Pad - Closed
Start
Current Position:  Shuttle Pad

        Sensors indicate current position to be on top of southern biodome.
There is some sort of space travelling device on a landing pad here.  Next
to one of its doors is a red button.  To the south is an elevator shaft,
with a slot next to the doors.  The doors are currently closed.
EndDesc
STOP

Shuttle Pad - Open
Start
Current Position:  Shuttle Pad

        Sensors indicate current position to be on top of southern biodome.
There is some sort of space travelling device on a landing pad here.  Next
to one of its doors is a red button.  To the south is an elevator shaft,
with a slot next to the doors.  The doors are currently open.
EndDesc
South
STOP

Engineering Entrance
Start
Current Position:  Circuitry Room

        Sensors indicate current position to be within some sort of room.
Circuitry lines the walls.  From here, there are twin sliding doors to the
east and west, while there is another area to the south from here.  There
is a closed door to the north.
EndDesc
East
South
West
STOP

Waiting Room
Start
Current Position:  Waiting Room

        Sensors indicate current position to be within some sort of room.  
There is a computer behind the desk here, next to which is a red power 
button.  There are sets of sliding doors to the south and north.  There is
an access slot next to the doors to the north.
EndDesc
South
North
STOP

Inside Office
Start
Current Position:  Office

        Sensors indicate current position to be inside some sort of office.
There is a desk here, upon which is a computer.  There is a red power button
next to the computer.  There is a set of sliding doors to the south.
EndDesc
South
STOP

Office30 - Closed
Start
Current Location:  Office

        Sensors indicate current position to be in the office of some sort
of medical personell.  There is an open doorway to the east here, while 
there is a closed door to the northwest with a biohazard symbol drawn on it.
Next to the door is an slot, above which is an electronic display and 
keypad.
EndDesc
East
STOP

Office30 - Open
Start
Current Location:  Office

        Sensors indicate current position to be in the office of some sort
of medical personell.  There is an open doorway to the east here, while 
there is an open door to the northwest.  Next to the door is an slot, above 
which is an electronic display and keypad.
EndDesc
NorthWest
East
STOP

BioLab1 Hall
EndDesc
West
SouthWest
STOP

Supply Room - Closed
Start
EndDesc
East
STOP

Supply Room - Open
Start
Current Location:  Supply Room
EndDesc
SouthEast
East
STOP

BioLab1 Laboratory - Syringe Taken
Start
Current Position:  Laboratory

        Sensors detect position to be in a laboratory.  There are shelves and
shelves of empty bottles here.  However, there are three full bottles here
on the shelf.  The first bottle is a red bottle, the second is a blue one,
and third is a green one.  From here, there is a hallway off to the 
northeast.
EndDesc
NorthEast
STOP

BioLab1 Laboratory - Syringe Untaken
Start
Current Position:  Laboratory

        Sensors detect position to be in a laboratory.  There are shelves and
shelves of empty bottles here.  However, there are three full bottles here
on the shelf.  The first bottle is a red bottle, the second is a blue one,
and third is a green one.  From here, there is a hallway off to the 
northeast.  There is an empty syringe lying on the shelf here.
EndDesc
NorthEast
STOP

BioLab1Hall
Start
EndDesc
West
SouthWest
STOP
