'RoomDesc
'
'Room Description Here
'
'End Desc
'Directions here
'STOP

Tube East-West
Start
Current Position:  In East-West Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
east and west.
EndDesc
East
West
STOP

Tube North-South
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.
EndDesc
North
South
STOP

City Entrance - Closed - Device Open
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  It is opened, and under it there is extensive
circuitry and wiring.  There also appears to be a lever in the device also.
Next to the device is a door, currently closed.  On the door is some writing.
To the south, the tubing continues on.
EndDesc
South
STOP

City Entrance - Closed
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  On the odd device appears to be a red button
and a keypad.  Next to the device is a door, currently closed.  On the door
is some writing.  To the south, the tubing continues on.
EndDesc
South
STOP

City Entrance - Opened
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  On the odd device appears to be a red button
and a keypad.  Next to the device is a door, currently open.  On the door is
some writing.  To the south, the tubing continues on.
EndDesc
North
South
STOP

City Entrance - Opened - Device Open
Start
Current Position:  In Tube

        Visual sensors report current position to be in a length of tubing.
Tubing is constructed of polymers, mostly durable plastics.  There is an
odd device in the north wall.  It is opened, and under it there is extensive
circuitry and wiring.  There also appears to be a lever in the device also.
Next to the device is a door, currently open.  On the door is some writing.
To the south, the tubing continues on.
EndDesc
North
South
STOP


Tube North-South - Power Unfixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a broken power line in the wall here in the east 
wall.
EndDesc
North
South
STOP

Tube North-South - Power Half Fixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a power line in the wall here in the east 
wall.  There is a power couplink lying over it, currently not welded to the
power line.
EndDesc
North
South
STOP

Tube North-South - Power Fixed
Start
Current Position:  In North-South Tube

        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and south.  There is a fixed power line in the wall here in the east 
wall.  At times, it gives off electrical sparks, but it seems to work.
EndDesc
North
South
STOP

Blocked Tube - Power Half Fixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system reports
no chemical atmosphere past collapsed tube.  The tubing here continues to 
the north.  There is a power line in the wall here in the east wall.  On it
is a power couplink.  The couplink is not welded on to the power line.  In 
the rubble of the collapsed tube is a contained fission explosive.
EndDesc
North
STOP

Blocked Tube - Power Fixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system reports
no chemical atmosphere past collapsed tube.  The tubing here continues to 
the north.  There is a fixed power line in the wall here in the east wall.  
At times, it gives off electrical sparks, but it seems to work.  On the 
rubble of the collapsed tube is a contained fission explosive.
EndDesc
North
STOP

Blocked Tube - Power Unfixed - Explosive Set
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a broken power line in the wall here in the
east wall.  On the rubble of the collapsed tube is a contained fission 
explosive.
EndDesc
North
STOP

Blocked Tube - Power Half Fixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is power line in the wall here in the east 
wall.  Placed over it is a power couplink which is not welded to the line.
There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Blocked Tube - Power Fixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a fixed power line in the wall here in the
east wall.  At times, it gives off electrical sparks, but it seems to work.
There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Blocked Tube - Power Unfixed
Start
Current Position:  In Tube

        Visual sensors report collapsed tube to the south.  CES system
reports no chemical atmosphere past collapsed tube.  The tubing here
continues to the north.  There is a broken power line in the wall here in the
east wall.  There is a heap of rubble blocking passage south.
EndDesc
North
STOP

Power Conduit
Start
Current Position:  In Tube

        Visual sensors report that the eastern tube ends here.  The tube
goes off to the west from here.  Sensors indicate a vacuum outside the
current tube area.  There is a large device in the east wall here.
EndDesc
West
STOP

Outside Biolab - Door Closed
Start
Current Position:  In Tube

        Visual sensors report there to be a closed door in the south wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  On the door appears to be a symbol and some writing.  Next
to the door is a slot.
EndDesc
West
East
STOP

Outside Biolab - Door Opened
Start
Current Position:  In Tube

        Visual sensors report there to be a open door in the south wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  Next to the door is a slot.
EndDesc
South
West
East
STOP

Tube Intersection
Start
Current Position:  Tube Intersection

        Visual sensors report there to be an open door in the south wall
here.  Sensors report an intersection of tubes comprised mostly of plastic
here.  Outside the tubes is a planetary vacuum.  No atmosphere detected
beyond tubing.  The tubes go off to the north, east, and west.  The door
is open to the south.
EndDesc
North
South
East
West
STOP

Outside Library or Security - Door Opened
Start
Current Position:  In Tube

        Visual sensors report there to be a opened door in the north wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  Next to the door is a slot.
EndDesc
North
East
West
STOP

Outside Library or Security - Door Closed
Start
Current Position:  In Tube

        Visual sensors report there to be a closed door in the north wall
here.  The plastic tube-substance surrounding sensors continues to the east
and the west.  On the door appears to be some writing.  Next to the door
is a slot.
EndDesc
West
East
STOP

Tube North-East
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
north and east.
EndDesc
North
East
STOP

Tube South-West
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
south and west.
EndDesc
South
West
STOP

Tube South-East
Start
Current Position:  In Tube
        
        There is a long tube stretching before visual sensors.  Sensors report
the tube to be surrounded by a planetary vacuum.  No atmosphere detected
beyond tubing.  The tube in which current location is in continues to the
south and east.
EndDesc
South
East
STOP

Sterilization Chamber2 - Outer Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  The one to the
north is open.
EndDesc
North
STOP

Sterilization Chamber2 - Inner Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  The one to the
west is open.
EndDesc
West
STOP

Sterilization Chamber2 - Closed
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and west.  Both are closed.
EndDesc
STOP

Sterilization Chamber - Outer Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  The one to the
north is open.
EndDesc
North
STOP

Sterilization Chamber - Inner Open
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  The one to the
south is open.
EndDesc
South
STOP

Sterilization Chamber - Closed
Start
Current Position:  Sterilization Chamber

        Sensors indicate Current Position to be within a Sterilization
Chamber.  The walls here are white.  Behind the walls is extensive
biotechnology, built into the walls and designed to sterilize the chamber.
There is a slot in the east wall, and an electronic screen and keypad under
that.  There are two doors here, to the north and south.  Both are closed.
EndDesc
STOP

Lobby - Closed
Start
Current Position:  White Room

        Sensors indicate Current Position to be within a white room.  There
is a computer terminal behind a desk here, with a red power button on it.
There is a closed door to the north, with a slot next to it.  Below the
slot is an electronic keypad and screen.  There is a hallway to the west.
EndDesc
West
STOP

Lobby - Open
Start
Current Position:  White Room

        Sensors indicate Current Position to be within a white room.  There
is a computer terminal behind a desk here, with a red power button on it.
There is an open door to the north, with a slot next to it.  Below the
slot is an electronic keypad and screen.  There is a hallway to the west.
EndDesc
North
West
STOP

Library Core
Start
Current Position:  Library Core

        Visual sensors report Current Position to be what seems to be the
equivalent of a library.  There are no books here, but there appears to be
a large amount of circuitry built in the walls here.  There is an open
archway to the east, where a large deal of the circuitry is detected.  There
is a doorway to the south, currently open.
EndDesc
East
South
STOP

Library Central Computer
Start
Current Position:  Library Central Computer Core

        Visual sensors report a large mainframe in this room.  There is a
large red power button next to the mainframe.  To the west is the Central
Library Core, and the exit.  The only feature of this room is the mainframe,
which is larger than any mainframe on internal records.
EndDesc
West
STOP

Security Armory
Start
Current Position:  Weapons Depot
EndDesc
South
STOP

Debriefing Room
Start
Current Position:  Large Room
EndDesc
South
STOP

Moniter Room - Video Playing
Start
Current Position:  Surveillance Center

        Sensors indicate current area to be a surveillance center for the
domed colony on Sirrus 5.  All but one of the monitors seems to have burned
out.  The lone monitor that is not burned out is playing some sort of video.
Below the monitor is a video slot, which has a video tape in it.  It is
currently playing.  There are a set of detailed controls below the monitors.
You may leave to the south.
EndDesc
South
STOP

Moniter Room
Start
Current Position:  Surveillance Center

        Sensors indicate current area to be a surveillance center for the
domed colony on Sirrus 5.  All but one of the monitors seems to have burned
out.  The lone monitor that is not burned out is monitoring an area of the
colony.  Below the monitor is a video slot, which has a video tape in it.  
There are a set of detailed controls below the monitors.  You may leave to 
the south.
EndDesc
South
STOP

Security Hall, West
Start
Current Position:  In Hallway

        Current position is within a long hallway.  The hallway continues to
the east and west.  There is an open doorway to the north from here.
EndDesc
West
North
East
STOP

Security Hall, East
Start
Current Position:  In Hallway

        Current position is within a long hallway.  The hallway continues to
the west.  There is an open doorway to the north from here.
EndDesc
West
North
STOP

Security Access
Start
Current Position:  Security Lobby

        Visual sensors report current position to be in a white-walled lobby.
There is a computer here, currently off.  Next to the computer is a red
button, inlaid with circuitry.  There is a long hallway to the east from
here, and there is a large room to the north.  There is a door to the south
from here, currently open.
EndDesc
North
East
South
STOP

Office30 - Closed
Start
Current Position:  Office

        Sensors indicate current position to be in the office of some sort
of medical personell.  There is an open doorway to the east here, while 
there is a closed door to the northwest with a biohazard symbol drawn on it.
Next to the door is an slot, above which is an electronic display and 
keypad.
EndDesc
East
STOP

Office30 - Open
Start
Current Position:  Office

        Sensors indicate current position to be in the office of some sort
of medical personell.  There is an open doorway to the east here, while 
there is an open door to the northwest.  Next to the door is an slot, above 
which is an electronic display and keypad.
EndDesc
NorthWest
East
STOP

Hall23
Start
Current Position:  Hall

        Sensors indicate current location to be in a hall.  The hall goes
to the west and southwest from here.
EndDesc
West
SouthWest
STOP

Supply Room - Closed
Start
Current Position:  Supply Room

        Sensors indicate current position to be in an empty supply room.
There is a hall to the east from here.  There is also a closed door to the
southeast here.
EndDesc
East
STOP

Supply Room - Open
Start
Current Position:  Supply Room

        Sensors indicate current position to be in an empty supply room.
There is a hall to the east from here.  There is also an open door to the
southeast here.
EndDesc
SouthEast
East
STOP

BioLab1 Laboratory - Syringe Taken
Start
Current Position:  Laboratory

        Sensors detect position to be in a laboratory.  There are shelves and
shelves of empty bottles here.  However, there are three full bottles here
on the shelf.  The first bottle is a red bottle, the second is a blue one,
and third is a green one.  From here, there is a hallway off to the 
northeast.
EndDesc
NorthEast
STOP

BioLab1 Laboratory - Syringe Untaken
Start
Current Position:  Laboratory

        Sensors detect position to be in a laboratory.  There are shelves and
shelves of empty bottles here.  However, there are three full bottles here
on the shelf.  The first bottle is a red bottle, the second is a blue one,
and third is a green one.  From here, there is a hallway off to the 
northeast.  There is an empty syringe lying on the shelf here.
EndDesc
NorthEast
STOP

Research Area - Vial Untaken
Start
Current Position:  Research Area

        Sensors indicate current position to be in some sort of research
area.  There is a hallway to the north from here.  There is also a group
of broken vials on the shelf here.  However, one of the vials is intact.
There is a hall to the east.
EndDesc
North
East
STOP

Research Area - Vial Taken
Start
Current Position:  Research Area

        Sensors indicate current position to be in some sort of research
area.  There is a hallway to the north from here.  There is also a group
of broken vials on the shelf here.  There is a hall to the east.
EndDesc
North
East
STOP

BioLockDoor - Open
Start
Current Position:  Biolock Door

        Sensors indicate current position to be near a huge biolock door to
the east.  It is open.  From here, you may go down a hall to the west.
EndDesc
West
East
STOP

BioLockDoor - Closed
Start
Current Position:  Biolock Door

        Sensors indicate current position to be near a huge biolock door to
the east.  The door can be easily opened by turning a wheel and then opening
it.  From here, you may go down a hall to the west.
EndDesc
West
STOP

Cage
Start
Current Position:  In Cage

        Sensors indicate current position to be within a cage.  Sensors
also detect there to be large amounts of radiation in this area.  In the
east wall of this cage is an alien, chained up to the wall by electrically
powered chains.  Also attached to the alien are scanners, monitering its
health condition.  The alien appears to be in some sort of stasis.  There 
is an open door to the west.
EndDesc
West
STOP


